# Generated by Django 5.2 on 2025-04-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_name', models.CharField(max_length=100)),
                ('Food_cat', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('img', models.URLField(default='https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/96/fa/14/restaurant.jpg?w=600&h=-1&s=1')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
