# Generated by Django 5.2 on 2025-04-09 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurants')),
            ],
        ),
    ]
